blue:
  replicaCount: 3
  image:
    repository: ashuop/ashu3456
    tag: latest
    pullPolicy: IfNotPresent

green:
  replicaCount: 3
  image:
    repository: ashuop/ashu3456
    tag: latest
    pullPolicy: IfNotPresent

service:
  name: blue-green
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: blue-green.example.com
      paths: ["/"]
